services:
  - type: web
    name: smc-quest-miniapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: 8505971843:AAHJDrETopJ8D_Ww9avB6MWbtpO_rnXXJqk
        sync: false
      - key: WEBHOOK_URL
        value: https://smc-quest-miniapp.onrender.com
      - key: 445677777
        sync: false
      - key: DATA_DIR
        value: /tmp
